site_name: SAP TechEd SEC364 Hands-On: Secure Microservices in Cloud Foundry Environment on SAP Cloud Platform
site_url: https://github.com/SAP-samples/cloud-cf-product-list
nav:
    - Overview: 
      - Home: index.md
      - Prepare Trial Account: 01_setup/README.md
      - Download Application: 02_clone/README.md
      - Secure Application: 09_secure/README.md
        - Flavor 1: Cloud native Spring Boot Application: 09_secure/Spring.md
        - Option 2: SAP Java Web Application: 09_secure/Java.md
        - Option 3: Cloud native Node.JS Application: 09_secure/Node.js.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
docs_dir: docs
repo_url: https://github.com/SAP-samples/cloud-cf-product-list